
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: bridge-deployment
  name: bridge-deployment
    tags:
    - java
spec:
  lifecycle: production
  owner: my-team
  type: service
